// Seeded demo founders. Flat shape matching the `profiles` table (no userId, isSeed: true).

type Seed = {
  name: string; age: number; initials: string; location: string; remoteOk: boolean;
  brings: "technical" | "business" | "design" | "operator";
  seeking: "technical" | "business" | "design" | "operator";
  stage: "idea" | "pre-seed" | "building" | "revenue";
  commitment: "full-time" | "nights-weekends" | "exploring";
  industries: string[]; pitch: string; equity: string; secondTime: boolean;
  gender: "man" | "woman" | "nonbinary";
  datingOpen: boolean;
  datingSeeking: ("man" | "woman" | "nonbinary")[];
  datingIntent: "long-term" | "see-where-it-goes" | "casual";
};

export const seedFounders: Seed[] = [
  { name: "Amara Kone", age: 31, initials: "AK", location: "San Francisco", remoteOk: true, brings: "technical", seeking: "business", stage: "pre-seed", commitment: "full-time", industries: ["Fintech", "Infrastructure", "AI"], pitch: "Ex-Stripe engineer. Build fast, obsess over reliability. Looking for a commercial co-founder who knows fintech go-to-market.", equity: "50/50 open", secondTime: true, gender: "woman", datingOpen: true, datingSeeking: ["man", "nonbinary"], datingIntent: "long-term" },
  { name: "Diego Ramos", age: 28, initials: "DR", location: "Austin", remoteOk: true, brings: "technical", seeking: "business", stage: "idea", commitment: "full-time", industries: ["AI", "Developer tools", "SaaS"], pitch: "ML engineer who shipped two 0→1 products. Want a business partner to turn an AI agent prototype into a company.", equity: "Slight founder premium", secondTime: false, gender: "man", datingOpen: true, datingSeeking: ["woman"], datingIntent: "see-where-it-goes" },
  { name: "Priya Nair", age: 34, initials: "PN", location: "San Francisco", remoteOk: false, brings: "technical", seeking: "business", stage: "building", commitment: "full-time", industries: ["Fintech", "SaaS"], pitch: "Full-stack lead, ex-Plaid. Prototype is live with 3 design partners. Need a co-founder to own sales and fundraising.", equity: "50/50 open", secondTime: true, gender: "woman", datingOpen: true, datingSeeking: ["man"], datingIntent: "long-term" },
  { name: "Marcus Webb", age: 39, initials: "MW", location: "Remote", remoteOk: true, brings: "business", seeking: "technical", stage: "pre-seed", commitment: "full-time", industries: ["Climate", "Hardware"], pitch: "Two exits on the commercial side. Have LOIs from enterprise buyers in climate. Need a technical co-founder yesterday.", equity: "Negotiable", secondTime: true, gender: "man", datingOpen: false, datingSeeking: ["woman"], datingIntent: "long-term" },
  { name: "Lena Fischer", age: 27, initials: "LF", location: "San Francisco", remoteOk: true, brings: "design", seeking: "technical", stage: "idea", commitment: "nights-weekends", industries: ["Consumer", "AI"], pitch: "Product designer from a top consumer app. Exploring an AI-native journaling idea nights and weekends.", equity: "50/50 open", secondTime: false, gender: "woman", datingOpen: true, datingSeeking: ["woman", "nonbinary"], datingIntent: "long-term" },
  { name: "Tomas Alvarez", age: 33, initials: "TA", location: "San Francisco", remoteOk: true, brings: "technical", seeking: "business", stage: "pre-seed", commitment: "full-time", industries: ["AI", "SaaS", "Fintech"], pitch: "Backend + infra specialist. Left a senior role to start something in AI-driven SaaS. Want a GTM-minded co-founder.", equity: "50/50 open", secondTime: false, gender: "man", datingOpen: true, datingSeeking: ["woman"], datingIntent: "long-term" },
  { name: "Sofia Greco", age: 30, initials: "SG", location: "San Francisco", remoteOk: true, brings: "operator", seeking: "technical", stage: "building", commitment: "full-time", industries: ["Marketplace", "SaaS"], pitch: "Early operator at two scale-ups. Can run ops, hiring, and growth. Looking for a technical founder with a live product.", equity: "Founding-team equity", secondTime: false, gender: "woman", datingOpen: true, datingSeeking: ["man", "woman"], datingIntent: "see-where-it-goes" },
  { name: "Raj Patel", age: 36, initials: "RP", location: "New York", remoteOk: false, brings: "business", seeking: "technical", stage: "revenue", commitment: "full-time", industries: ["Fintech", "SaaS"], pitch: "Bootstrapped a fintech tool to $200k ARR solo. Need a technical co-founder to scale the platform properly.", equity: "Equity for the right CTO", secondTime: true, gender: "man", datingOpen: false, datingSeeking: ["woman"], datingIntent: "long-term" },
  { name: "Yuki Tanaka", age: 29, initials: "YT", location: "San Francisco", remoteOk: true, brings: "technical", seeking: "design", stage: "idea", commitment: "exploring", industries: ["Consumer", "AI"], pitch: "Mobile engineer exploring a consumer AI idea. Casually looking for a design-minded partner — no rush.", equity: "TBD", secondTime: false, gender: "nonbinary", datingOpen: true, datingSeeking: ["woman", "man", "nonbinary"], datingIntent: "casual" },
  { name: "Hannah Brooks", age: 32, initials: "HB", location: "San Francisco", remoteOk: true, brings: "technical", seeking: "business", stage: "pre-seed", commitment: "full-time", industries: ["Healthtech", "AI", "SaaS"], pitch: "Health-data engineer, ex-research lab. Building an AI clinical assistant. Need a co-founder for sales and regulation.", equity: "50/50 open", secondTime: false, gender: "woman", datingOpen: true, datingSeeking: ["man"], datingIntent: "long-term" },
  { name: "Nadia Hassan", age: 29, initials: "NH", location: "San Francisco", remoteOk: true, brings: "technical", seeking: "business", stage: "building", commitment: "full-time", industries: ["Fintech", "AI", "SaaS"], pitch: "Ex-Square engineer building AI underwriting infra. Live pilot with two lenders. Want a commercial co-founder who loves fintech.", equity: "50/50 open", secondTime: false, gender: "woman", datingOpen: true, datingSeeking: ["man"], datingIntent: "long-term" },
  { name: "Grace Liu", age: 31, initials: "GL", location: "San Francisco", remoteOk: true, brings: "business", seeking: "technical", stage: "pre-seed", commitment: "full-time", industries: ["Healthtech", "AI"], pitch: "Healthcare operator turned founder. Have payer LOIs for an AI care-navigation product. Looking for a technical co-founder — and maybe more.", equity: "Negotiable", secondTime: true, gender: "woman", datingOpen: true, datingSeeking: ["man"], datingIntent: "see-where-it-goes" },
  { name: "Bianca Rossi", age: 27, initials: "BR", location: "Austin", remoteOk: true, brings: "design", seeking: "technical", stage: "idea", commitment: "full-time", industries: ["Consumer", "AI", "SaaS"], pitch: "Product designer who shipped a top-50 consumer app. Prototyping an AI creativity tool. Want a technical partner who sweats the details.", equity: "50/50 open", secondTime: false, gender: "woman", datingOpen: true, datingSeeking: ["man", "nonbinary"], datingIntent: "long-term" },
  { name: "Elena Vasquez", age: 33, initials: "EV", location: "San Francisco", remoteOk: true, brings: "technical", seeking: "business", stage: "pre-seed", commitment: "full-time", industries: ["Climate", "SaaS", "AI"], pitch: "Climate-tech engineer, ex-Tesla. Building grid-optimization software. Need a co-founder who can sell into utilities.", equity: "50/50 open", secondTime: true, gender: "woman", datingOpen: true, datingSeeking: ["man", "woman"], datingIntent: "long-term" },
  { name: "Maya Okonkwo", age: 30, initials: "MO", location: "San Francisco", remoteOk: true, brings: "operator", seeking: "technical", stage: "building", commitment: "full-time", industries: ["Marketplace", "Fintech", "Consumer"], pitch: "Scaled ops at two marketplaces from seed to Series B. Want to co-found something in consumer fintech with a strong technical partner.", equity: "Founding-team equity", secondTime: false, gender: "woman", datingOpen: true, datingSeeking: ["man"], datingIntent: "casual" },
  { name: "Chloe Bennett", age: 28, initials: "CB", location: "New York", remoteOk: true, brings: "business", seeking: "technical", stage: "pre-seed", commitment: "full-time", industries: ["Fintech", "AI"], pitch: "Ex-VC turned founder. Raised a pre-seed for an AI bookkeeping tool. Looking for a technical co-founder who wants to go all the way.", equity: "Negotiable", secondTime: false, gender: "woman", datingOpen: true, datingSeeking: ["man"], datingIntent: "long-term" },
];
